version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
  - package-ecosystem: 'npm'
    directory: "/web"
    schedule:
      interval: 'weekly'
    labels:
      - 'scope: web'
      - 'dependencies'
    groups:
      production-dependencies-major:
        dependency-type: "production"
        update-types:
          - "major"
      production-dependencies-minor:
        dependency-type: "production"
        update-types:
         - "minor"
         - "patch"
      development-dependencies-major:
        dependency-type: "development"
        update-types:
          - "major"
      development-dependencies-minor:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'scope: scripts'
      - 'dependencies'
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"