version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
  - package-ecosystem: 'npm'
    directory: "/web"
    schedule:
      interval: 'weekly'
    labels:
      - 'scope: web'
      - 'dependencies'
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'scope: scripts'
      - 'dependencies'
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"