import pytest

from scripts.cluster_analysis import main, initial_metadata_pass
from scripts.clusters import clusters


@pytest.mark.skip()
def test_main():
    main()


def test_initial_metadata():
    input_meta = "data/metadata.csv"
    clus_to_run = clusters.keys()
    cols = ['strain', 'date', 'division', 'host', 'substitutions', 'deletions', 'Nextstrain_clade', 'country',
            'gisaid_epi_isl', 'coverage', 'QC_overall_status', 'Nextclade_pango']
    display_name_to_clus = {cluster["display_name"]: key for key, cluster in clusters.items()}
    Nextstrain_clades, Nextstrain_clades_display_names, all_countries, n_total = initial_metadata_pass(clus_to_run,
                                                                                                       cols,
                                                                                                       display_name_to_clus,
                                                                                                       input_meta)
    assert Nextstrain_clades == ['20A', '24A (Omicron)']
    assert Nextstrain_clades_display_names == ['24A (Omicron)']
    assert all_countries == ['Afghanistan', 'Australia', 'Cambodia', 'Japan', ]
    assert n_total == 10


def test_initial_metadata_zipped_slow():
    input_meta = "data/metadata.csv.gz"
    clus_to_run = clusters.keys()
    cols = ['strain', 'date', 'division', 'host', 'substitutions', 'deletions', 'Nextstrain_clade', 'country',
            'gisaid_epi_isl', 'coverage', 'QC_overall_status', 'Nextclade_pango']
    display_name_to_clus = {cluster["display_name"]: key for key, cluster in clusters.items()}
    nextstrain_clades, nextstrain_clades_display_names, all_countries, n_total = initial_metadata_pass(clus_to_run,
                                                                                                       cols,
                                                                                                       display_name_to_clus,
                                                                                                       input_meta,
                                                                                                       mode='slow')
    assert nextstrain_clades == ['20A', '24A (Omicron)']
    assert nextstrain_clades_display_names == ['24A (Omicron)']
    assert all_countries == ['Afghanistan', 'Australia', 'Cambodia', 'Japan', ]
    assert n_total == 10


def test_initial_metadata_zipped_fast():
    input_meta = "data/metadata.csv.gz"
    clus_to_run = clusters.keys()
    cols = ['strain', 'date', 'division', 'host', 'substitutions', 'deletions', 'Nextstrain_clade', 'country',
            'gisaid_epi_isl', 'coverage', 'QC_overall_status', 'Nextclade_pango']
    display_name_to_clus = {cluster["display_name"]: key for key, cluster in clusters.items()}
    nextstrain_clades, nextstrain_clades_display_names, all_countries, n_total = initial_metadata_pass(clus_to_run,
                                                                                                       cols,
                                                                                                       display_name_to_clus,
                                                                                                       input_meta,
                                                                                                       mode='fast')
    assert nextstrain_clades == ['20A', '24A (Omicron)']
    assert nextstrain_clades_display_names == ['24A (Omicron)']
    assert all_countries == ['Afghanistan', 'Australia', 'Cambodia', 'Japan', ]
    assert n_total == 10


def test_initial_metadata_zipped_full_slow():
    input_meta = "../../metadata.tsv.gz"
    clus_to_run = clusters.keys()
    cols = ['strain', 'date', 'division', 'host', 'substitutions', 'deletions', 'Nextstrain_clade', 'country',
            'gisaid_epi_isl', 'coverage', 'QC_overall_status', 'Nextclade_pango']
    display_name_to_clus = {cluster["display_name"]: key for key, cluster in clusters.items()}
    nextstrain_clades, nextstrain_clades_display_names, all_countries, n_total = initial_metadata_pass(clus_to_run,
                                                                                                       cols,
                                                                                                       display_name_to_clus,
                                                                                                       input_meta,
                                                                                                       mode='slow')
    assert nextstrain_clades == [
        ' (Omicron)',
        '19A',
        '19B',
        '20A',
        '20B',
        '20C',
        '20D',
        '20E (EU1)',
        '20F',
        '20G',
        '20H (Beta, V2)',
        '20I (Alpha, V1)',
        '20J (Gamma, V3)',
        '21A (Delta)',
        '21B (Kappa)',
        '21C (Epsilon)',
        '21D (Eta)',
        '21E (Theta)',
        '21F (Iota)',
        '21G (Lambda)',
        '21H (Mu)',
        '21I (Delta)',
        '21J (Delta)',
        '21K (Omicron)',
        '21L (Omicron)',
        '21M (Omicron)',
        '22A (Omicron)',
        '22B (Omicron)',
        '22C (Omicron)',
        '22D (Omicron)',
        '22E (Omicron)',
        '22F (Omicron)',
        '23A (Omicron)',
        '23B (Omicron)',
        '23C (Omicron)',
        '23D (Omicron)',
        '23E (Omicron)',
        '23F (Omicron)',
        '23G (Omicron)',
        '23H (Omicron)',
        '23I (Omicron)',
        '24A (Omicron)',
        '24B (Omicron)',
        '24C (Omicron)',
        '24D (Omicron)',
        '24E (Omicron)',
        '24F (Omicron)',
        '24G (Omicron)',
        '24H (Omicron)',
        '24I (Omicron)',
        '25A (Omicron)',
        'recombinant',
    ]
    assert nextstrain_clades_display_names == ['20E (EU1)',
                                               '20H (Beta, V2)',
                                               '20I (Alpha, V1)',
                                               '20J (Gamma, V3)',
                                               '21A (Delta)',
                                               '21B (Kappa)',
                                               '21C (Epsilon)',
                                               '21D (Eta)',
                                               '21F (Iota)',
                                               '21G (Lambda)',
                                               '21H (Mu)',
                                               '21I (Delta)',
                                               '21J (Delta)',
                                               '21K (Omicron)',
                                               '21L (Omicron)',
                                               '21M (Omicron)',
                                               '22A (Omicron)',
                                               '22B (Omicron)',
                                               '22C (Omicron)',
                                               '22D (Omicron)',
                                               '22E (Omicron)',
                                               '22F (Omicron)',
                                               '23A (Omicron)',
                                               '23B (Omicron)',
                                               '23C (Omicron)',
                                               '23D (Omicron)',
                                               '23E (Omicron)',
                                               '23F (Omicron)',
                                               '23G (Omicron)',
                                               '23H (Omicron)',
                                               '23I (Omicron)',
                                               '24A (Omicron)',
                                               '24B (Omicron)',
                                               '24C (Omicron)',
                                               '24D (Omicron)',
                                               '24E (Omicron)',
                                               '24F (Omicron)',
                                               '24G (Omicron)',
                                               '24H (Omicron)',
                                               '24I (Omicron)',
                                               '25A (Omicron)',
                                               'recombinant']
    assert all_countries == ['Afghanistan',
                             'Albania',
                             'Algeria',
                             'Andorra',
                             'Angola',
                             'Antigua and Barbuda',
                             'Argentina',
                             'Armenia',
                             'Aruba',
                             'Australia',
                             'Austria',
                             'Azerbaijan',
                             'Bahamas',
                             'Bahrain',
                             'Bangladesh',
                             'Barbados',
                             'Belarus',
                             'Belgium',
                             'Belize',
                             'Benin',
                             'Bermuda',
                             'Bhutan',
                             'Bolivia',
                             'Bonaire',
                             'Bosnia and Herzegovina',
                             'Botswana',
                             'Brazil',
                             'Brunei',
                             'Bulgaria',
                             'Burkina Faso',
                             'Burundi',
                             'Cabo Verde',
                             'Cambodia',
                             'Cameroon',
                             'Canada',
                             'Central African Republic',
                             'Chad',
                             'Chile',
                             'China',
                             'Colombia',
                             'Cook Islands',
                             'Costa Rica',
                             'Croatia',
                             'Cuba',
                             'Curacao',
                             'Cyprus',
                             'Czech Republic',
                             "Côte d'Ivoire",
                             'Democratic Republic of the Congo',
                             'Denmark',
                             'Djibouti',
                             'Dominica',
                             'Dominican Republic',
                             'Ecuador',
                             'Egypt',
                             'El Salvador',
                             'Equatorial Guinea',
                             'Estonia',
                             'Eswatini',
                             'Ethiopia',
                             'Fiji',
                             'Finland',
                             'France',
                             'French Guiana',
                             'French Polynesia',
                             'Gabon',
                             'Gambia',
                             'Georgia',
                             'Germany',
                             'Ghana',
                             'Gibraltar',
                             'Greece',
                             'Grenada',
                             'Guadeloupe',
                             'Guatemala',
                             'Guinea',
                             'Guinea-Bissau',
                             'Guyana',
                             'Haiti',
                             'Honduras',
                             'Hong Kong',
                             'Hungary',
                             'Iceland',
                             'India',
                             'Indonesia',
                             'Iran',
                             'Iraq',
                             'Ireland',
                             'Israel',
                             'Italy',
                             'Jamaica',
                             'Japan',
                             'Jersey',
                             'Jordan',
                             'Kazakhstan',
                             'Kenya',
                             'Kiribati',
                             'Kosovo',
                             'Kuwait',
                             'Kyrgyzstan',
                             'Laos',
                             'Latvia',
                             'Lebanon',
                             'Lesotho',
                             'Liberia',
                             'Libya',
                             'Liechtenstein',
                             'Lithuania',
                             'Luxembourg',
                             'Madagascar',
                             'Malawi',
                             'Malaysia',
                             'Maldives',
                             'Mali',
                             'Malta',
                             'Marshall Islands',
                             'Mauritania',
                             'Mauritius',
                             'Mexico',
                             'Micronesia',
                             'Moldova',
                             'Monaco',
                             'Mongolia',
                             'Montenegro',
                             'Morocco',
                             'Mozambique',
                             'Myanmar',
                             'Namibia',
                             'Nepal',
                             'Netherlands',
                             'New Caledonia',
                             'New Zealand',
                             'Nicaragua',
                             'Niger',
                             'Nigeria',
                             'Niue',
                             'North Macedonia',
                             'Northern Mariana Islands',
                             'Norway',
                             'Oman',
                             'Pakistan',
                             'Palau',
                             'Palestine',
                             'Panama',
                             'Papua New Guinea',
                             'Paraguay',
                             'Peru',
                             'Philippines',
                             'Poland',
                             'Portugal',
                             'Puerto Rico',
                             'Qatar',
                             'Republic of the Congo',
                             'Romania',
                             'Russia',
                             'Rwanda',
                             'Saint Barthélemy',
                             'Saint Kitts and Nevis',
                             'Saint Lucia',
                             'Saint Martin',
                             'Saint Vincent and the Grenadines',
                             'Samoa',
                             'Sao Tome and Principe',
                             'Saudi Arabia',
                             'Senegal',
                             'Serbia',
                             'Seychelles',
                             'Sierra Leone',
                             'Singapore',
                             'Sint Maarten',
                             'Slovakia',
                             'Slovenia',
                             'Solomon Islands',
                             'Somalia',
                             'South Africa',
                             'South Korea',
                             'South Sudan',
                             'Spain',
                             'Sri Lanka',
                             'Sudan',
                             'Suriname',
                             'Sweden',
                             'Switzerland',
                             'Syria',
                             'Taiwan',
                             'Tanzania',
                             'Thailand',
                             'Timor-Leste',
                             'Togo',
                             'Tonga',
                             'Trinidad and Tobago',
                             'Tunisia',
                             'Turkey',
                             'USA',
                             'Uganda',
                             'Ukraine',
                             'Union of the Comoros',
                             'United Arab Emirates',
                             'United Kingdom',
                             'Uruguay',
                             'Uzbekistan',
                             'Vanuatu',
                             'Venezuela',
                             'Vietnam',
                             'Zambia',
                             'Zimbabwe']
    assert n_total == 16860043


def test_initial_metadata_zipped_full_fast():
    input_meta = "../../metadata.tsv.gz"
    clus_to_run = clusters.keys()
    cols = ['strain', 'date', 'division', 'host', 'substitutions', 'deletions', 'Nextstrain_clade', 'country',
            'gisaid_epi_isl', 'coverage', 'QC_overall_status', 'Nextclade_pango']
    display_name_to_clus = {cluster["display_name"]: key for key, cluster in clusters.items()}
    nextstrain_clades, nextstrain_clades_display_names, all_countries, n_total = initial_metadata_pass(clus_to_run,
                                                                                                       cols,
                                                                                                       display_name_to_clus,
                                                                                                       input_meta,
                                                                                                       mode='fast')
    assert nextstrain_clades == [
        ' (Omicron)',
        '19A',
        '19B',
        '20A',
        '20B',
        '20C',
        '20D',
        '20E (EU1)',
        '20F',
        '20G',
        '20H (Beta, V2)',
        '20I (Alpha, V1)',
        '20J (Gamma, V3)',
        '21A (Delta)',
        '21B (Kappa)',
        '21C (Epsilon)',
        '21D (Eta)',
        '21E (Theta)',
        '21F (Iota)',
        '21G (Lambda)',
        '21H (Mu)',
        '21I (Delta)',
        '21J (Delta)',
        '21K (Omicron)',
        '21L (Omicron)',
        '21M (Omicron)',
        '22A (Omicron)',
        '22B (Omicron)',
        '22C (Omicron)',
        '22D (Omicron)',
        '22E (Omicron)',
        '22F (Omicron)',
        '23A (Omicron)',
        '23B (Omicron)',
        '23C (Omicron)',
        '23D (Omicron)',
        '23E (Omicron)',
        '23F (Omicron)',
        '23G (Omicron)',
        '23H (Omicron)',
        '23I (Omicron)',
        '24A (Omicron)',
        '24B (Omicron)',
        '24C (Omicron)',
        '24D (Omicron)',
        '24E (Omicron)',
        '24F (Omicron)',
        '24G (Omicron)',
        '24H (Omicron)',
        '24I (Omicron)',
        '25A (Omicron)',
        'recombinant',
    ]
    assert nextstrain_clades_display_names == ['20E (EU1)',
                                               '20H (Beta, V2)',
                                               '20I (Alpha, V1)',
                                               '20J (Gamma, V3)',
                                               '21A (Delta)',
                                               '21B (Kappa)',
                                               '21C (Epsilon)',
                                               '21D (Eta)',
                                               '21F (Iota)',
                                               '21G (Lambda)',
                                               '21H (Mu)',
                                               '21I (Delta)',
                                               '21J (Delta)',
                                               '21K (Omicron)',
                                               '21L (Omicron)',
                                               '21M (Omicron)',
                                               '22A (Omicron)',
                                               '22B (Omicron)',
                                               '22C (Omicron)',
                                               '22D (Omicron)',
                                               '22E (Omicron)',
                                               '22F (Omicron)',
                                               '23A (Omicron)',
                                               '23B (Omicron)',
                                               '23C (Omicron)',
                                               '23D (Omicron)',
                                               '23E (Omicron)',
                                               '23F (Omicron)',
                                               '23G (Omicron)',
                                               '23H (Omicron)',
                                               '23I (Omicron)',
                                               '24A (Omicron)',
                                               '24B (Omicron)',
                                               '24C (Omicron)',
                                               '24D (Omicron)',
                                               '24E (Omicron)',
                                               '24F (Omicron)',
                                               '24G (Omicron)',
                                               '24H (Omicron)',
                                               '24I (Omicron)',
                                               '25A (Omicron)',
                                               'recombinant']
    assert all_countries == ['Afghanistan',
                             'Albania',
                             'Algeria',
                             'Andorra',
                             'Angola',
                             'Antigua and Barbuda',
                             'Argentina',
                             'Armenia',
                             'Aruba',
                             'Australia',
                             'Austria',
                             'Azerbaijan',
                             'Bahamas',
                             'Bahrain',
                             'Bangladesh',
                             'Barbados',
                             'Belarus',
                             'Belgium',
                             'Belize',
                             'Benin',
                             'Bermuda',
                             'Bhutan',
                             'Bolivia',
                             'Bonaire',
                             'Bosnia and Herzegovina',
                             'Botswana',
                             'Brazil',
                             'Brunei',
                             'Bulgaria',
                             'Burkina Faso',
                             'Burundi',
                             'Cabo Verde',
                             'Cambodia',
                             'Cameroon',
                             'Canada',
                             'Central African Republic',
                             'Chad',
                             'Chile',
                             'China',
                             'Colombia',
                             'Cook Islands',
                             'Costa Rica',
                             'Croatia',
                             'Cuba',
                             'Curacao',
                             'Cyprus',
                             'Czech Republic',
                             "Côte d'Ivoire",
                             'Democratic Republic of the Congo',
                             'Denmark',
                             'Djibouti',
                             'Dominica',
                             'Dominican Republic',
                             'Ecuador',
                             'Egypt',
                             'El Salvador',
                             'Equatorial Guinea',
                             'Estonia',
                             'Eswatini',
                             'Ethiopia',
                             'Fiji',
                             'Finland',
                             'France',
                             'French Guiana',
                             'French Polynesia',
                             'Gabon',
                             'Gambia',
                             'Georgia',
                             'Germany',
                             'Ghana',
                             'Gibraltar',
                             'Greece',
                             'Grenada',
                             'Guadeloupe',
                             'Guatemala',
                             'Guinea',
                             'Guinea-Bissau',
                             'Guyana',
                             'Haiti',
                             'Honduras',
                             'Hong Kong',
                             'Hungary',
                             'Iceland',
                             'India',
                             'Indonesia',
                             'Iran',
                             'Iraq',
                             'Ireland',
                             'Israel',
                             'Italy',
                             'Jamaica',
                             'Japan',
                             'Jersey',
                             'Jordan',
                             'Kazakhstan',
                             'Kenya',
                             'Kiribati',
                             'Kosovo',
                             'Kuwait',
                             'Kyrgyzstan',
                             'Laos',
                             'Latvia',
                             'Lebanon',
                             'Lesotho',
                             'Liberia',
                             'Libya',
                             'Liechtenstein',
                             'Lithuania',
                             'Luxembourg',
                             'Madagascar',
                             'Malawi',
                             'Malaysia',
                             'Maldives',
                             'Mali',
                             'Malta',
                             'Marshall Islands',
                             'Mauritania',
                             'Mauritius',
                             'Mexico',
                             'Micronesia',
                             'Moldova',
                             'Monaco',
                             'Mongolia',
                             'Montenegro',
                             'Morocco',
                             'Mozambique',
                             'Myanmar',
                             'Namibia',
                             'Nepal',
                             'Netherlands',
                             'New Caledonia',
                             'New Zealand',
                             'Nicaragua',
                             'Niger',
                             'Nigeria',
                             'Niue',
                             'North Macedonia',
                             'Northern Mariana Islands',
                             'Norway',
                             'Oman',
                             'Pakistan',
                             'Palau',
                             'Palestine',
                             'Panama',
                             'Papua New Guinea',
                             'Paraguay',
                             'Peru',
                             'Philippines',
                             'Poland',
                             'Portugal',
                             'Puerto Rico',
                             'Qatar',
                             'Republic of the Congo',
                             'Romania',
                             'Russia',
                             'Rwanda',
                             'Saint Barthélemy',
                             'Saint Kitts and Nevis',
                             'Saint Lucia',
                             'Saint Martin',
                             'Saint Vincent and the Grenadines',
                             'Samoa',
                             'Sao Tome and Principe',
                             'Saudi Arabia',
                             'Senegal',
                             'Serbia',
                             'Seychelles',
                             'Sierra Leone',
                             'Singapore',
                             'Sint Maarten',
                             'Slovakia',
                             'Slovenia',
                             'Solomon Islands',
                             'Somalia',
                             'South Africa',
                             'South Korea',
                             'South Sudan',
                             'Spain',
                             'Sri Lanka',
                             'Sudan',
                             'Suriname',
                             'Sweden',
                             'Switzerland',
                             'Syria',
                             'Taiwan',
                             'Tanzania',
                             'Thailand',
                             'Timor-Leste',
                             'Togo',
                             'Tonga',
                             'Trinidad and Tobago',
                             'Tunisia',
                             'Turkey',
                             'USA',
                             'Uganda',
                             'Ukraine',
                             'Union of the Comoros',
                             'United Arab Emirates',
                             'United Kingdom',
                             'Uruguay',
                             'Uzbekistan',
                             'Vanuatu',
                             'Venezuela',
                             'Vietnam',
                             'Zambia',
                             'Zimbabwe']
    assert n_total == 16860043
