version: 2.1

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.3.0

major_branches_only: &major_branches_only
  filters:
    branches:
      only:
        - master
        - release

jobs:
  Build-And-Deploy:
    resource_class: medium

    docker:
      - image: cimg/python:3.8.10-node

    environment:
      PROD_ENABLE_TYPE_CHECKS: 0

    steps:
      - git-shallow-clone/checkout:
          depth: 1
          fetch_depth: 1

      - restore_cache:
          name: "Restore web application build cache"
          keys:
            - cache-web-v3-{{ arch }}-{{ checksum "web/yarn.lock" }}

      - run:
          name: "Install AWS CLI"
          command: |
            curl -fsS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -oqq awscliv2.zip
            sudo ./aws/install --update

      - run:
          name: "Build web application (branch << pipeline.git.branch >>)"
          command: |
            set -x
            cd web
            yarn install --frozen-lockfile
            cp .env.example .env
            yarn lint:ci
            yarn prod:build:ci

      - save_cache:
          name: "Save web application build cache"
          key: cache-web-v3-{{ arch }}-{{ checksum "web/yarn.lock" }}
          paths:
            - web/.cache
            - web/.build/production/tmp/cache

      - run:
          name: "Clear AWS S3 bucket (branch << pipeline.git.branch >>): html files, web root, app bundle"
          command: |
            aws s3 rm s3://${AWS_S3_BUCKET} --recursive --exclude "proteins/*" --exclude "acknowledgements/*"

      - run:
          name: "Deploy to AWS S3 (branch << pipeline.git.branch >>): app bundle"
          command: |
            cd web/.build/production/web
            aws s3 cp --recursive --cache-control "max-age=2592000, public" "_next/" "s3://${AWS_S3_BUCKET}/_next/"

      - run:
          name: "Deploy to AWS S3 (branch << pipeline.git.branch >>): web root"
          command: |
            cd web/.build/production/web
            aws s3 cp --recursive \
              --exclude "_next/*" \
              --exclude "*.html" \
              --exclude "acknowledgements/*" \
              --exclude "proteins/*" \
            "./" "s3://${AWS_S3_BUCKET}/"

      - run:
          name: "Deploy to AWS S3 (branch << pipeline.git.branch >>): html files"
          command: |
            cd web/.build/production/web
            find * -type f -name "*.html" -print0 | xargs -0 -P4 -n1 -I '{}' -- bash -c '\
              file={}; \
              aws s3 cp \
                --content-type "text/html" \
                --cache-control "no-cache" \
                --metadata-directive REPLACE \
                  $file \
                  s3://${AWS_S3_BUCKET}/${file%.html}'

      - run:
          name: "Invalidate AWS Cloudfront cache (branch << pipeline.git.branch >>): html files, web root, app bundle"
          command: |
            aws cloudfront create-invalidation \
              --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} \
              --paths "/*"

      - run:
          name: "Clear AWS S3 bucket (branch << pipeline.git.branch >>): large static files"
          command: |
            aws s3 rm s3://${AWS_S3_BUCKET} --recursive --exclude "*" --include "proteins/" --include "acknowledgements/"

      - run:
          name: "Deploy to AWS S3 (branch << pipeline.git.branch >>): large static files "
          command: |
            cd web/.build/production/web
            aws s3 cp --recursive --cache-control "max-age=7200, public" --metadata-directive REPLACE "proteins/" "s3://${AWS_S3_BUCKET}/proteins/"
            aws s3 cp --recursive --cache-control "max-age=7200, public" --metadata-directive REPLACE "acknowledgements/" "s3://${AWS_S3_BUCKET}/acknowledgements/"

      - run:
          name: "Invalidate AWS Cloudfront cache (branch << pipeline.git.branch >>): large static files"
          command: |
            aws cloudfront create-invalidation \
              --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} \
              --paths "/acknowledgements/*" "/proteins/*"

workflows:
  version: 2
  build:
    jobs:
      - Build-And-Deploy:
          context: covariants_<< pipeline.git.branch >>
          <<: *major_branches_only
