name: "run storybook tests"

runs:
  using: "composite"
  steps:
    - name: "[test] Run component tests"
      run: |
        echo "[test] Run component tests"
        cd web
        npx storybook build
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:6006 && yarn test-storybook"
      shell: bash